### ISSUE TITLE
Git Branch not showing

### ISSUE THREAD

**Issue by getthemike** [urda/urda.bash#11]
RVM shows but it doesn't tell me my branch.
Can it only do one or the other?

**Comment by urda** [comment]
It should be able to do both (`git` and `rvm`) @getthemike 

This is what I see: https://asciinema.org/a/37542

Make sure you have the latest `urda.bash` I don't embed any version information at this time so that's going to be your best bet.

**Comment by getthemike** [comment]
![image](https://cloud.githubusercontent.com/assets/697694/13364916/e0bf5880-dc9f-11e5-8a62-d9d3a6627cef.png)

**Comment by getthemike** [comment]
Is there a setup step I'm missing?

**Comment by urda** [comment]
So I know the key line is:

```
if type __git_ps1 > /dev/null 2>&1 ; then
```
https://github.com/urda/urda.bash/blob/8f4b16a3cbc5990222318e25aa21a1063a863c35/bashrc#L147

I don't remember having to do anything to make `__git_ps1` available on my machine. I'm looking into it.

**Comment by urda** [comment]
What is the output of `type __git_ps1` from your prompt @getthemike ?

**Comment by getthemike** [comment]
command not found

**Comment by urda** [comment]
OK so we know why it isn't working, let me see what one has to do to get that working on OS X. How did you install `git` on your machine?

**Comment by getthemike** [comment]
Do not recall. Default method me-thinks. Looking into it now.

**Comment by urda** [comment]
My `git` is through homebrew:

```bash
$ brew list | ack git
git
git-flow
```

**Comment by urda** [comment]
This should also be of help: https://gist.github.com/trey/2722934

**Comment by urda** [comment]
`urda.bash` appears to be alright after I did some spot checking this morning. In order for this shell, or any other shell that depends on `__git_ps1` you'll need to have your `git` installed correctly. I do recommend `brew` to do so.

If you have any more questions let me know, I'll see about updating documentation or the shell to check this condition in a later release.
